version: 2.1

orbs:
  python: circleci/python@1.4.0 # Latest as of 11.05.21
  
jobs:
  build:
    docker:
      - image: cimg/python:3.9.5-browsers
      
    executor: python/default
    
    steps:
      - checkout

      - restore_cache: # Download and cache dependencies
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: running tests
          command: |
            . venv/bin/activate
            python3 -m pytest -v --driver Chrome
      - store_test_results: 
          path: test-results
      - store_artifacts:
          path: test-reports
          destination: test-reports